---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/events/{id}":
    post:
      summary: Creates an event
      tags:
      - Events
      operationId: CreateEvent
      parameters: []
      responses:
        '200':
          description: event created
          content:
            application/json:
              schema:
                oneOf:
                - "$ref": "#/components/schemas/CreateEventResponse"
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - "$ref": "#/components/schemas/CreateEventRequest"
    get:
      summary: Retrieves an event
      operationId: GetEvent
      tags:
      - Events
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: events found
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/GetEventResponse"
  "/api/v1/guests/{id}":
    post:
      summary: Creates an guest
      tags:
      - Guests
      operationId: CreateGuest
      parameters: []
      responses:
        '200':
          description: guest created
          content:
            application/json:
              schema:
                oneOf:
                - "$ref": "#/components/schemas/CreateGuestResponse"
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - "$ref": "#/components/schemas/CreateGuestRequest"
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
