---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/events/{id}":
    get:
      summary: Retrieves an event
      operationId: GetEvent
      tags:
      - Events
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: event found
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    id:
                      type: string
                    name:
                      type: string
                    description:
                      type: text
                required:
                - data
        '404':
          description: event not found
  "/api/v1/events":
    post:
      summary: Creates an event
      tags:
      - Events
      operationId: CreateEvent
      parameters: []
      responses:
        '500':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                possible_dates:
                  type: array
                  items:
                    type: string
        required: true
  "/api/v1/guests/{id}":
    post:
      summary: Creates an guest
      tags:
      - Guests
      operationId: CreateGuest
      parameters: []
      responses:
        '200':
          description: guest created
          content:
            application/json:
              schema:
                oneOf:
                - "$ref": "#/components/schemas/CreateGuestResponse"
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - "$ref": "#/components/schemas/CreateGuestRequest"
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
